### ISSUE TITLE
Asbru-cm doesn't start anymore after upgrading to 6.0

### ISSUE THREAD

**Issue by bierbo** [asbru-cm/asbru-cm#329]
**Describe the bug**
After upgrading asbru-cm to version 6.0.0-1.fc30 (via dnf, Fedora 30) asbru-cm doesn't start anymore.
Starting via Application menu does nothing, starting via command line throws following error:
`[lbischof@pluto]~% asbru-cm
Typelib file for namespace 'Wnck', version '3.0' not found at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/PACUtils.pm line 54.
Compilation failed in require at /usr/share/asbru-cm/lib/PACMain.pm line 53.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/PACMain.pm line 53.
Compilation failed in require at /usr/bin/asbru-cm line 92.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 92.`

**To Reproduce**
1. Install asbru-cm via "official" way on Fedora 30 (KDE Spin)
2. start asbru (either via app menu or command line)
3. See error

**Expected behavior**
Program should start

**Desktop (please complete the following information):**
 - OS: Fedora KDE Spin
 - Version: 30

**Additional Information**
Following packages have been installed as dependency (dnf transaction information):
eränderte Pakete:
    Installieren perl-Cairo-GObject-1.004-12.fc30.x86_64            @fedora
    Installieren perl-Glib-Object-Introspection-0.047-1.fc30.x86_64 @fedora
    Installieren perl-Gtk3-0.034-6.fc30.noarch                      @fedora
    Installieren perl-Gtk3-SimpleList-0.18-2.fc30.noarch            @fedora
    Upgrade      asbru-cm-6.0.0-1.fc30.noarch                       @asbru-cm_asbru-cm
    Upgraded     asbru-cm-5.2.1-1.fc30.noarch                       @@System

Current workaround is downgrading to 5.x via dnf.

**Comment by gfrenoy** [comment]
Can you check if you have package ```libwnck3``` installed on your machine ?

And if it's not installed, to add it

```
sudo dnf install libwnck3
```

And let us know if it fixed the issue ?

I do test with Fedora 30 Gnome where that package is installed but maybe it's not the case with KDE so we'll need to add it to the RPM dependencies...

**Comment by bierbo** [comment]
YES, this solves the problem!
Thanks for your help!

**Comment by gfrenoy** [comment]
Thanks for letting us know!

I've added the dependency to the RPM package.
