### ISSUE TITLE
Syntax error at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 360 (Loki on EL 7.8)

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#714]
Hi ...

Getting this when starting latest loki build on EL 7.8:

[mockbuild@testc7 ~]$ asbru-cm 
syntax error at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 360, near "}{"
Global symbol "$wk" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 361.
Global symbol "$wk" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 362.
Global symbol "$w" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 363.
Global symbol "$w" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 364.
Global symbol "%keybindings" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 369.
Global symbol "%keybindings" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 370.
Global symbol "%keybindings" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 371.
Global symbol "$default_cfg" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 372.
Global symbol "$self" requires explicit package name at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 374.
syntax error at /usr/share/asbru-cm/lib/PACKeyBindings.pm line 376, near "}"
/usr/share/asbru-cm/lib/PACKeyBindings.pm has too many errors.
Compilation failed in require at /usr/share/asbru-cm/lib/PACConfig.pm line 52.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/PACConfig.pm line 52.
Compilation failed in require at /usr/share/asbru-cm/lib/PACMain.pm line 73.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/PACMain.pm line 73.
Compilation failed in require at /usr/bin/asbru-cm line 93.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 93.
[mockbuild@testc7 ~]$ 

Any ideas ?
Thanks.

**Comment by gfrenoy** [comment]
I would guess you have an old version of perl that does not support that particular syntax `%{$self->{cfg}}{$w}` ... 
Can you try splitting the line in two separate instructions:

`
        my $cfg = $self->{cfg};
        my $wk = $$cfg{$w};
`

**Comment by popxunga** [comment]
Hi ...
EL 8.2 reports: This is perl 5, version 26, subversion 3 (v5.26.3)
EL 7.8 reports: This is perl 5, version 16, subversion 3 (v5.16.3)
Let me try spit the line as suggested.

**Comment by popxunga** [comment]
I confirm that replacing the instruction on line 360 of /usr/share/asbru-cm/lib/PACKeyBindings.pm as follows resolves the issue:
```
        # my $wk = %{$self->{cfg}}{$w};
        my $cfg = $self->{cfg};
        my $wk = $$cfg{$w};
```

**Comment by popxunga** [comment]
Working fine now .... Thanks !
Closing ...
