### ISSUE TITLE
Request for Appimage

### ISSUE THREAD

**Issue by trueshanti** [asbru-cm/asbru-cm#804]
Its quite a mission to bring asbru to work in opensuse-15.2

i would hope you would build an Appimage x-) 

thank you
-c-

**Comment by gfrenoy** [comment]
There is a script to generate an AppImage for Ásbrú, see https://github.com/asbru-cm/asbru-cm/tree/master/dist/appimage

We are looking for options to automate the build and publish the generated file somewhere.  Any suggestion will be welcome.

**Comment by trueshanti** [comment]
where would be a good place to report errors with the appimage-buildscript ? because its not quite doing what it should

**Comment by trueshanti** [comment]
`# sh -x ./make_appimage.sh
+ readonly ASBRU_RELEASE=release
+ ASBRU_RELEASE=release
+ readonly UBUNTU_RELEASE=bionic
+ UBUNTU_RELEASE=bionic
+ readonly APPDIR=./AppDir
+ APPDIR=./AppDir
+ main
++ cloudsmith ls pkgs asbru-cm/release -q 'distribution:ubuntu/bionic filename:.deb$' -F pretty_json
++ jq -r '.data[0].version_orig'
Getting list of packages ... OK
+ local ASBRU_VERSION=6.3.2-1
+ '[' -z 6.3.2-1 ']'
++ cloudsmith repos ls asbru-cm/release -F pretty_json
++ jq -r '.data[0].gpg_keys[0].fingerprint_short'
Getting list of repositories ... ERROR
Failed to get list of repositories! (status: 404 - Not Found)

Detail: Not found.
Hint: This usually means the user/org is wrong or not visible.
+ local CLOUDSMITH_KEY=
+ '[' -z '' ']'
+ echo 'ERROR: Unable to retrieve cloudsmith repository key for asbru-cm/release, build aborted.'
ERROR: Unable to retrieve cloudsmith repository key for asbru-cm/release, build aborted.
+ exit 2`

#### 

`# cloudsmith repos ls asbru-cm/release
Getting list of repositories ... ERROR
Failed to get list of repositories! (status: 404 - Not Found)

Detail: Not found.
Hint: This usually means the user/org is wrong or not visible.
`

**Comment by gfrenoy** [comment]
Mmm, so it looks like `cloudsmith repos ls asbru-cm/release` requires you to login on cloudsmith first, do I get this right ?

Do you mind to do a `cloudsmith login` first (you'll need to create an account...) ?

**Comment by gfrenoy** [comment]
Fyi, I built the image for the latest realease in my environment and added it to the "assets" of the [6.3.2 release](https://github.com/asbru-cm/asbru-cm/releases/6.3.2), so you can download it from the following link:
  https://github.com/asbru-cm/asbru-cm/releases/download/6.3.2/asbru-cm-6.3.2-1-x86_64.AppImage

It works fine for me but consider this as a "beta" :-)

And let us know if it works for you on the target platform...

**Comment by trueshanti** [comment]
> Do you mind to do a `cloudsmith login` first (you'll need to create an account...) ?

doesnt change a thing :(

**Comment by trueshanti** [comment]
> And let us know if it works for you on the target platform...
sadly didnt for LEAP15.2 ..

strace here:
https://susepaste.org/37608469

**Comment by trueshanti** [comment]
@gfrenoy :

# i am logged in:
cloudsmith whoami
Retrieving your authentication status from the API ... OK
You are authenticated as:
Christoph (slug: christoph, email: office@xxx.xx)

# status is OK:
cloudsmith check service
Retrieving service status ... OK
The service endpoint is: https://api.cloudsmith.io
The service status is:   Cloudsmith API is operational.
The service version is:  0.56.121 (maybe out-of-date)
The API library used by this CLI tool is built against service version: 0.54.15

# i can check status:
cloudsmith status asbru-cm/release/asbru-cm_622-1_alldeb-Ok6
Getting status of asbru-cm_622-1_alldeb-Ok6 in asbru-cm/release ... OK
The package status is: Completed / Fully Synchronised

# but listing repos drops error:
cloudsmith repos ls asbru-cm/release -F pretty_json

and since this is part of the build-script , it fails.

So i guess the repos are not public ?

**Comment by trueshanti** [comment]
ups

**Comment by gfrenoy** [comment]
So, yes, the repo is apparently not public.  So I guess something is wrong in the script to generate the AppImage.

In #811, others have found the following error message when launching the generated AppImage:

```
~/Downloads> ./asbru-cm-6.3.2-1-x86_64.AppImage 
uuid.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xed00080)
```

Does this sound any bell to anybody ?

Strangely enough, when run on Ubuntu, it works fine...

**Comment by trueshanti** [comment]
strace from trying the image on opensuse 15.2:

https://paste.opensuse.org/58975263

**Comment by barkely128** [comment]
I think it might be, because the uuid.c library was compiled against a different perl version, from which is being launched? Maybe it has something to do with PATH environment in the Appimage. It seems that it's launching local perl.

Checked the AppImage:
$ find . -type f -name perl
./usr/bin/perl
./usr/share/lintian/overrides/perl

Why I think that way it's, because in #811 we have a little difference in our errors:
OP:
0xde00080, needed 0xed00080
ME:
0xde00080, needed 0xeb00080

That "needed" perl seems to be the generated against local perl.

**Comment by barkely128** [comment]
Yeah it seems to be a screwes up PATH variable to me. I don't like your .env file too much:

$ grep ^PATH $APPDIR/.env 
PATH=$APPDIR/usr/lib/x86_64-linux-gnu/libgtk-3-0:$PATH:$APPDIR/usr/lib/glib-networking:$PATH:$APPDIR/usr/lib/x86_64-linux-gnu/glib-2.0:$PATH:$APPDIR/usr/lib/x86_64-linux-gnu/libgtk2.0-0:$PATH:$APPDIR/usr/lib/dconf:$PATH:$APPDIR/usr/lib/openssh:$PATH:$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0:$PATH:$APPDIR/usr/bin:$PATH

What I see here is that you're adding $PATH variable, right after $APPDIR/usr/lib/x86_64-linux-gnu/libgtk-3-0:$PATH

If it's the system's PATH, there is no way the rest the directories are going to take precedence over system's PATH. So basically everything after it is screwed.

So I tried to fix it like this:
squashfs-root]$ export APPDIR=$(pwd)

Then remove all the excess PATH variables and move it to be the very last one:

export PATH=$APPDIR/usr/lib/x86_64-linux-gnu/libgtk-3-0:$APPDIR/usr/lib/glib-networking:$APPDIR/usr/lib/x86_64-linux-gnu/glib-2.0:$APPDIR/usr/lib/x86_64-linux-gnu/libgtk2.0-0:$APPDIR/usr/lib/dconf:$APPDIR/usr/lib/openssh:$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0:$APPDIR/usr/bin:$PATH

$ cd opt/asbru/
$ ./asbru-cm

And Asbru launches without any issues.

**Comment by gfrenoy** [comment]
@barkely128 Thanks for your help and the great troubleshooting work done so far !

But I'm not sure to understand why this `.env` is wrong ... I don't control it at all during the AppImage build process.

Is there anything I can change in https://github.com/asbru-cm/asbru-cm/tree/master/dist/appimage to fix this ?

**Comment by barkely128** [comment]
No probs, sorry don't have experience with appImage here to tell you what exactly is happening during the build.

Maybe you can explicitly add the "PATH" variable like this in the recipe yaml. But it's only a guess:
        runtime:
                env:
                        PATH: $APPDIR/usr/lib/x86_64-linux-gnu/libgtk-3-0:$APPDIR/usr/lib/glib-networking:$APPDIR/usr/lib/x86_64-linux-gnu/glib-2.0:$APPDIR/usr/lib/x86_64-linux-gnu/libgtk2.0-0:$APPDIR/usr/lib/dconf:$APPDIR/usr/lib/openssh:$APPDIR/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0:$APPDIR/usr/bin

**Comment by Cris70** [comment]
This is on OpenSuse Tumbleweed:
```
cris - ~/Applications > ./asbru-cm-6.3.2-2-x86_64_321fdd13a27e6918b96f9789a0b3900a.AppImage
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
uuid.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xed00080)
```

**Comment by trueshanti** [comment]
Test on openSUSE 15.3:

# ./asbru-cm-6.3.2-2-x86_64.AppImage 
Typelib file for namespace 'Gtk', version '3.0' not found at /tmp/.mount_asbru-esN5wh/usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-esN5wh/opt/asbru/lib/ex/SortedTreeStore.pm line 37.
Compilation failed in require at /tmp/.mount_asbru-esN5wh/opt/asbru/lib/PACMain.pm line 48.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-esN5wh/opt/asbru/lib/PACMain.pm line 48.
Compilation failed in require at /tmp/.mount_asbru-esN5wh/usr/bin/asbru-cm line 93.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-esN5wh/usr/bin/asbru-cm line 93.

**Comment by opalmay** [comment]
> Test on openSUSE 15.3:
> # ./asbru-cm-6.3.2-2-x86_64.AppImage
> 
> Typelib file for namespace 'Gtk', version '3.0' not found at /tmp/.mount_asbru-esN5wh/usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 108.
> BEGIN failed--compilation aborted at /tmp/.mount_asbru-esN5wh/opt/asbru/lib/ex/SortedTreeStore.pm line 37.
> Compilation failed in require at /tmp/.mount_asbru-esN5wh/opt/asbru/lib/PACMain.pm line 48.
> BEGIN failed--compilation aborted at /tmp/.mount_asbru-esN5wh/opt/asbru/lib/PACMain.pm line 48.
> Compilation failed in require at /tmp/.mount_asbru-esN5wh/usr/bin/asbru-cm line 93.
> BEGIN failed--compilation aborted at /tmp/.mount_asbru-esN5wh/usr/bin/asbru-cm line 93.

Having the same also on 15.3 :(

**Comment by gfrenoy** [comment]
Does anyone of you know which kind of support we can get from the AppImage community ?  I mean, if any...?

**Comment by trueshanti** [comment]
@gfrenoy : 

./asbru-cm-6.3.2-2-x86_64.AppImage 
Typelib file for namespace 'Gtk', version '3.0' not found at /tmp/.mount_asbru-le4nxe/usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-le4nxe/opt/asbru/lib/ex/SortedTreeStore.pm line 37.
Compilation failed in require at /tmp/.mount_asbru-le4nxe/opt/asbru/lib/PACMain.pm line 48.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-le4nxe/opt/asbru/lib/PACMain.pm line 48.
Compilation failed in require at /tmp/.mount_asbru-le4nxe/usr/bin/asbru-cm line 93.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-le4nxe/usr/bin/asbru-cm line 93.

**Comment by marcheschi** [comment]
Hi 
I have also the same error on Opensuse 15.3
asbru-cm-6.3.2-2-x86_64_321fdd13a27e6918b96f9789a0b3900a.AppImage GDK_BACKEND=x11 asbru-cm
/usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
INFO: bad start up parameter GDK_BACKEND=x11
Typelib file for namespace 'Gtk', version '3.0' not found at /tmp/.mount_asbru-QeUuuJ/usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-QeUuuJ/opt/asbru/lib/ex/SortedTreeStore.pm line 37.
Compilation failed in require at /tmp/.mount_asbru-QeUuuJ/opt/asbru/lib/PACMain.pm line 48.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-QeUuuJ/opt/asbru/lib/PACMain.pm line 48.
Compilation failed in require at /tmp/.mount_asbru-QeUuuJ/usr/bin/asbru-cm line 93.
BEGIN failed--compilation aborted at /tmp/.mount_asbru-QeUuuJ/usr/bin/asbru-cm line 93.

**Comment by marcheschi** [comment]
> Its quite a mission to bring asbru to work in opensuse-15.2
> 
> i would hope you would build an Appimage x-)
> 
> thank you -c-

Hi, after some troubleshooting I make Asbru-cm work on Opensuse 15.3, (I think it can work also on 15.2). 

This is a perl software, so there is no reason of malfunctioning.

What I did:
first:
`$ git clone https://github.com/asbru-cm/asbru-cm.git`
`$ cd asbru-cm`
After, with Yast I downgraded two packages:

perl-Crypt-CBC to 2.33-bp153.1.15
![image](https://user-images.githubusercontent.com/3910408/146030988-726c22e1-dadd-4931-a6ec-8209f7495f63.png)

perl-Gtk3 to 0.038-lp153.11.15
![image](https://user-images.githubusercontent.com/3910408/146031203-80804393-d8f6-44a5-950c-0f2ebdb6f8e7.png)

After that, we can execute asbru-cm in the folder:
`$ ./absru`

That's it.
I hope this helps other Opensuse Users.
Thank you
Paolo

**Comment by gfrenoy** [comment]
> after some troubleshooting I make Asbru-cm work on Opensuse 15.3

Thanks for the feedback Paolo but this issue is dedicated to the "AppImage" version of Ásbrú.  What you describe is probably more related to #816.

This should not prevent you from contributing, please continue, that's great !  But try to stay on topic :)  Thanks.

**Comment by henry701** [comment]
@gfrenoy I think I'll try my hand on this after the holidays. I have a (currently not public-facing) project for dockerizing Asbrù and it's not turning out very well, however, it does provide a solid base for a self-contained AppImage of Asbrù using musl libc (Alpine-based).

**Comment by henry701** [comment]
> Appimage gives problems with Wayland `GLib-GIO-ERROR **: 09:21:44.785: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'` unfortunately the developer of AppImage does not agree with Wayland. it seems to me that the package that is the most functional in every sense is Flatpak

This issue occurs on the current `master` branch AppImage or the one from Loki branch (`appimage-raw`) #912? If testing on master, could you try using [this one](https://www.appimagehub.com/p/1796061) instead and check if you have better luck?

**Comment by wcasanova** [comment]
> > Appimage gives problems with Wayland `GLib-GIO-ERROR **: 09:21:44.785: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'` unfortunately the developer of AppImage does not agree with Wayland. it seems to me that the package that is the most functional in every sense is Flatpak
> 
> This issue occurs on the current `master` branch AppImage or the one from Loki branch (`appimage-raw`) #912? If testing on master, could you try using [this one](https://www.appimagehub.com/p/1796061) instead and check if you have better luck?

Yes, that's exactly what I tried.
asbru-cm-6.4.0-alpha.1.appimage

**Comment by henry701** [comment]
> > > Appimage gives problems with Wayland `GLib-GIO-ERROR **: 09:21:44.785: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'` unfortunately the developer of AppImage does not agree with Wayland. it seems to me that the package that is the most functional in every sense is Flatpak
> > 
> > 
> > This issue occurs on the current `master` branch AppImage or the one from Loki branch (`appimage-raw`) #912? If testing on master, could you try using [this one](https://www.appimagehub.com/p/1796061) instead and check if you have better luck?
> 
> Yes, that's exactly what I tried. asbru-cm-6.4.0-alpha.1.appimage

Damn. Does this also happen when running directly from the Perl source on your system, or does it only happen inside the AppImage? If it only happens inside the AppImage, maybe I can try pinning the GTK and other package versions to make the AppImage more stable.

**Comment by wcasanova** [comment]
I'm using Fedora Silverblue, preferably I install everything as Flatpak or AppImage, some things with toolbox/distrobox.
I try to keep layered packages to a minimum.

at the moment it works like this.
GDK_BACKEND=x11 ./asbru-cm-6.4.0-alpha.1.appimage

**Comment by henry701** [comment]
> I'm using Fedora Silverblue, preferably I install everything as Flatpak or AppImage, some things with toolbox/distrobox. I try to keep layered packages to a minimum.
> 
> at the moment it works like this. GDK_BACKEND=x11 ./asbru-cm-6.4.0-alpha.1.appimage

When I have some time later I'll install it in a VM and try to repro, then change some versions and see if that fixes the problem. Thanks for the system details!

**Comment by henry701** [comment]
It was happening because of an environment variable leak: XDG_DATA_DIRS was concatenating the existing environment variable. Removing that fixes the issue. Diff: https://github.com/henry701/asbru-cm/commit/171b6d8a0d380b58349f8bce274cfc4f578b7ad9

Workaround for running under Wayland, for now:

`LD_LIBRARY_PATH= XDG_DATA_DIRS= ./asbru-cm-6.4.0-alpha.1.appimage`

Let me know if it works @wcasanova

**Comment by wcasanova** [comment]
@henry701 it works.

```LD_LIBRARY_PATH= XDG_DATA_DIRS= ./asbru-cm-6.4.0-alpha.1.appimage
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 12716
INFO: Language detected : es_CL.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/var/home/user/.config/asbru'
INFO: Used config file '/var/home/user/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/tmp/.mount_asbru-311Wl1/opt/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon

(asbru-cm:12716): Gtk-CRITICAL **: 09:42:57.279: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
INFO: Finishing (asbru-cm) with pid 12716
INFO: Finished Ásbrú Connection Manager 6.4.0 (asbru-cm) (PID:12716)...```

**Comment by henry701** [comment]
Great! @gfrenoy can you please cherry-pick https://github.com/henry701/asbru-cm/commit/171b6d8a0d380b58349f8bce274cfc4f578b7ad9?

**Comment by wcasanova** [comment]
another option to solve this, is to use toolbox/distrobox in Fedora Silverblue

```
toolbox create
toolbox enter
curl -s https://packagecloud.io/install/repositories/asbru-cm/v5/script.rpm.sh | sudo bash
exit
toolbox run asbru-cm

**Comment by gfrenoy** [comment]
> Great! @gfrenoy can you please cherry-pick [henry701@171b6d8](https://github.com/henry701/asbru-cm/commit/171b6d8a0d380b58349f8bce274cfc4f578b7ad9)?

Certainly !

The latest and greatest version (6.4.0-alpha3) is now available on [AppImageHub](https://www.appimagehub.com/p/1796061/).

**Comment by trueshanti** [comment]
i love it !! - i'd rate that as solved ;-)

**Comment by Fabick75** [comment]
Hi, there are any possibilites that you put the AppImage builded inside the GitHUB page with the other versions? Avoiding to go on appimagehub.com ? This may be practical for automatic script tha check for a new version and download it automatically. Thanks

**Comment by gfrenoy** [comment]
Whenever 6.4.0 will be released, it will be done manually.

But if anyone has an idea on how to do this automatically, please let me know :)

**Comment by henry701** [comment]
> Whenever 6.4.0 will be released, it will be done manually.
> 
> But if anyone has an idea on how to do this automatically, please let me know :)

Attaching the built AppImage on GitHub Releases using either the existing CI system or GitHub Actions could work?

**Comment by gfrenoy** [comment]
I'd guess so ... We are using Travis CI today.  See https://github.com/asbru-cm/asbru-cm/blob/loki/.travis.yml ; I did not investigate this but if anyone has some suggestions or ideas, they will be very welcome.

**Comment by gfrenoy** [comment]
See in the latest release notes, the AppImage is available in the "assets" of the release.

@henry701 again, thanks a million for your help!  You are the hero on this one :)
